# Generated by Django 5.1.2 on 2024-12-27 00:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='createAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='birthday',
            new_name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telephone',
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome_completo',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
